// export const ADD_CONVERSATION_SUCCESS = "ADD_CONVERSATION_SUCCESS";

// export const ADD_CONVERSATION_FAILED = "ADD_CONVERSATION_FAILED";

// export const RECEIVE_CONVERSATION = "RECEIVE_CONVERSATION";

// export const FETCH_CONVERSATIONS = "FETCH_CONVERSATIONS";
